# implement the following features:
# Each park has a unique name and admission price, as well as a way to read that data
# 2.  park can list all the vehicles that entered the park
# 3.  park can list all the passengers that entered the park
# 4.  park can calculate revenue generated. Revenue is generated by charging the admission price per adult that entered the park.
class Park

    attr_reader :name,
                :admission

    def initialize(name, admission)
        @name = name
        @admission = name
    end
end