# implement the following features:
# 2.  park can list all the vehicles that entered the park
# 3.  park can list all the passengers that entered the park
# 4.  park can calculate revenue generated. Revenue is generated by charging the admission price per adult that entered the park.
class Park

    attr_reader :name,
                :admission,
                :park_vehicles

    def initialize(name, admission)
        @name = name
        @admission = admission
        @park_vehicles = []
    end

    def visiting_vehicle(vehicle)
        @park_vehicles << vehicle
    end
end