require './lib/vehicle'
require "./lib/passenger"
require "./lib/park_spec"

RSpec.configure do |config|
  config.formatter = :documentation
end

RSpec.describe Park do
  before(:each) do
    @park = Park.new
    @park_1 = Park.new({park_name: 'Park 1', admission_price: 10})
    @park_2 = Park.new({park_name: 'Park 2', admission_price: 20})
    @park_2 = Park.new({park_name: 'Park 3', admission_price: 30})
  end

  describe '#initialize' do
    it 'can initialize' do
      expect(@park).to be_an_instance_of(Park)
    end
  end

  describe '#name' do
    it 'has a name' do
      expect(@park_1.name).to eq("Park 1")
      expect(@park_2.name).to eq("Park 2")
      expect(@park_3.name).to eq("Park 3")
    end
  end

  describe '#admission price' do
    it 'has a price per person for admission' do
      expect(@park_1.admission_price).to eq(10)
      expect(@park_2.admission_price).to eq(20)
      expect(@park_2.admission_price).to eq(30)
    end
  end
end







#You have been contracted by the National Park Service to create a program that can track revenue for its parks. Specifically, they would like you to implement the following features:

#   1. Each park has a unique name and admission price, as well as a way to read that data

# In order to pass this IC, you'll need to have completed all prior requirements, as well as completing at least one of the requirements below. (It's recommended to try to complete all of the below requirements if possible.)

#   2. Each park can list all the vehicles that entered the park
#   3. Each park can list all the passengers that entered the park
#   4. Each park can calculate revenue generated. Revenue is generated by charging the admission price per adult that entered the park.

# Build upon your existing code from the first two iterations to implement this functionality.
